server:
  port: 8080
spring:
  application:
    name: dangdang-zuul
#zuul:
#  routes:
#    qianfeng:
#        path: /it/**
#        url: http://localhost:8100
#    pay:
#      path: /pay/**
#      url: http://localhost:8201
#      user:
#        path: /api/**
#        serviceId: DANGDANG-USER
  zipkin:
    base-url: http://localhost:8700/
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
ribbon:
  ConnectTimeout: 5000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 5000 #请求处理的超时时间